"""
Stage 03 - Generate the SYNTHETIC maintenance and incident ticket corpus.

Why: the charter proposes "maintenance/incident text data" as a source. No real mining
ticket system is available to this project, so the tickets are generated by rule, with a
fixed seed, from a documented template bank. They carry a category label, which lets the
text-mining component (C8) be evaluated with a confusion matrix instead of only producing
unverifiable topics.

Everything here is synthetic. Ticket text deliberately contains asset IDs, IP addresses,
usernames, protocol names and malware family names so that indicator extraction can be
tested against a known answer key (`gt_entities`).

Output: data/raw/synthetic_maintenance_tickets.csv (one row = one ticket)
"""
from __future__ import annotations

import sys
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import DATA_RAW, OUT_TABLES, SEED, env_stamp, get_logger, sha256, write_json

LOG = get_logger("s03_tickets")
rng = np.random.default_rng(SEED + 7)

START = datetime(2019, 4, 1)

TEMPLATES = {
    "security_incident": [
        "Repeated failed remote logins for account {user} from {ip} against the {target} on {asset}. "
        "SOC asked to review; account temporarily disabled pending confirmation.",
        "Unusual {proto} traffic observed from {asset} at {site} towards {ip}. Volume far above the "
        "normal baseline for this device. Suspected scanning activity.",
        "Antivirus on the engineering workstation flagged {malware} after a contractor connected a USB "
        "drive at {site}. Machine isolated from the OT network for imaging.",
        "Vendor account {user} logged into the OT jump host outside the approved maintenance window and "
        "opened the {target}. No change ticket exists for this work.",
        "Possible credential sharing: the same account {user} authenticated from {ip} and a second address "
        "within a few minutes. Access review requested for {site}.",
    ],
    "network_fault": [
        "Intermittent link loss between the {site} radio bridge and the core switch. {proto} sessions from "
        "{asset} time out during the fault window.",
        "High latency on the {site} microwave backhaul. Telemetry from {asset} arriving late, historian "
        "shows gaps of several minutes.",
        "DHCP exhaustion at {site}; new devices cannot obtain an address. Affected range includes {ip}.",
        "Firewall rule change blocked {proto} polling to {asset}; control room lost trend data until the "
        "rule was reverted.",
    ],
    "mechanical": [
        "Conveyor drive bearing at {site} running hot. Vibration readings above the alarm threshold; "
        "replacement scheduled for the next shutdown.",
        "Haul truck hydraulic leak reported by operator at {site}. Unit removed from service, no network "
        "impact to {asset}.",
        "Crusher liner wear beyond limit at {site}. Production rate reduced until the liner is replaced.",
        "Pump seal failure at the {site} dewatering station. Standby pump started automatically.",
    ],
    "instrumentation": [
        "Sensor {asset} at {site} reporting values outside the calibrated range. Calibration certificate "
        "expired, technician assigned.",
        "Thermostat on {asset} drifting by several degrees against the reference probe. Scheduled for "
        "recalibration.",
        "GPS tracker on the {site} light vehicle fleet dropping position fixes; firmware update pending.",
        "Modbus register map on {asset} does not match the documented configuration after a vendor visit.",
    ],
    "access_request": [
        "Contractor {user} requires temporary remote access to the {target} at {site} for a commissioning "
        "task. Approval and MFA enrolment required before access is granted.",
        "Account {user} requests privilege elevation on {asset} to complete firmware maintenance.",
        "Request to open {proto} from the vendor network to {asset} for diagnostics. Security review "
        "required before the rule is added.",
        "Offboarding: disable account {user} and revoke remote access tokens issued for {site}.",
    ],
}

SITES = ["PIT-A", "PIT-B", "PLANT-01", "TAILINGS-01", "WORKSHOP-01", "CAMP-01", "HQ-WHK", "PORT-WVB"]
PROTOCOLS = ["Modbus/TCP", "DNP3", "MQTT", "SSH", "RDP", "HTTPS", "SNMP"]
MALWARE = ["Industroyer", "TRITON", "Conficker", "Emotet", "BlackEnergy", "Ryuk"]
TARGETS = ["SCADA HMI", "historian", "PLC engineering workstation", "fleet management portal",
           "maintenance portal", "CCTV recorder"]
PRIORITY = ["P1", "P2", "P3", "P4"]


def main(n_tickets: int = 320) -> None:
    assets = pd.read_csv(DATA_RAW / "mining_asset_inventory.csv")
    users = pd.read_csv(DATA_RAW / "mining_user_directory.csv")

    cats = list(TEMPLATES)
    weights = np.array([0.22, 0.20, 0.24, 0.18, 0.16])
    rows = []
    for i in range(n_tickets):
        cat = str(rng.choice(cats, p=weights))
        tpl = str(rng.choice(TEMPLATES[cat]))
        asset = assets.sample(1, random_state=int(rng.integers(1e6))).iloc[0]
        user = users.sample(1, random_state=int(rng.integers(1e6))).iloc[0]
        ip = f"{rng.integers(10, 220)}.{rng.integers(0, 255)}.{rng.integers(0, 255)}.{rng.integers(2, 250)}"
        fills = {
            "user": user.username,
            "ip": ip,
            "asset": asset.asset_id,
            "site": str(rng.choice(SITES)),
            "proto": str(rng.choice(PROTOCOLS)),
            "malware": str(rng.choice(MALWARE)),
            "target": str(rng.choice(TARGETS)),
        }
        text = tpl.format(**fills)
        used = {k: v for k, v in fills.items() if "{" + k + "}" in tpl}
        ts = START + timedelta(days=int(rng.integers(0, 30)),
                               hours=int(rng.integers(0, 24)),
                               minutes=int(rng.integers(0, 60)))
        rows.append({
            "ticket_id": f"TKT{i+1:05d}",
            "opened_at": ts,
            "category": cat,
            "priority": str(rng.choice(PRIORITY, p=[0.08, 0.22, 0.45, 0.25])),
            "site": fills["site"],
            "asset_id": asset.asset_id,
            "reported_by": user.username,
            "text": text,
            "gt_entities": "|".join(f"{k}={v}" for k, v in sorted(used.items())),
            "data_status": "SYNTHETIC",
        })

    df = pd.DataFrame(rows).sort_values("opened_at").reset_index(drop=True)
    out = DATA_RAW / "synthetic_maintenance_tickets.csv"
    df.to_csv(out, index=False)

    write_json({
        "generator": "src/s03_generate_tickets.py",
        "seed": SEED + 7,
        "rows": int(len(df)),
        "categories": df["category"].value_counts().to_dict(),
        "sha256": sha256(out),
        "data_status": "SYNTHETIC - template-generated, no real ticket content",
        "env": env_stamp(),
    }, OUT_TABLES / "provenance_synthetic_tickets.json")
    LOG.info("tickets=%d categories=%s", len(df), df["category"].value_counts().to_dict())


if __name__ == "__main__":
    main()
