"""
Stage 04 (Capstone STEP 1) - Data inventory, data dictionary and data-quality profile.

Plain English: this script opens every raw dataset without changing it, counts rows and
columns, measures missing values and duplicates, works out what each column means
(timestamp, user, device, IP, network, authentication, label, text, numeric, categorical)
and writes three evidence tables that the report and the marking rubric ask for.

Outputs
  outputs/tables/data_inventory.csv   - one row per dataset
  outputs/tables/data_dictionary.csv  - one row per column of every dataset
  outputs/tables/data_quality.csv     - duplicate/missing/constant-column findings
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import DATA_RAW, OUT_TABLES, env_stamp, get_logger, sha256, write_json

LOG = get_logger("s04_inventory")

# dataset key -> (path, provenance, licence/status, role in the project)
SOURCES = {
    "iot_fridge":      (DATA_RAW / "ton_iot_gh/Train_Test_IoT_dataset/Train_Test_IoT_Fridge.csv",
                        "ToN_IoT (UNSW Canberra) - IoT telemetry", "public research dataset", "IIoT telemetry"),
    "iot_garage_door": (DATA_RAW / "ton_iot_gh/Train_Test_IoT_dataset/Train_Test_IoT_Garage_Door.csv",
                        "ToN_IoT (UNSW Canberra) - IoT telemetry", "public research dataset", "IIoT telemetry"),
    "iot_gps_tracker": (DATA_RAW / "ton_iot_gh/Train_Test_IoT_dataset/Train_Test_IoT_GPS_Tracker.csv",
                        "ToN_IoT (UNSW Canberra) - IoT telemetry", "public research dataset", "IIoT telemetry"),
    "iot_modbus":      (DATA_RAW / "ton_iot_gh/Train_Test_IoT_dataset/Train_Test_IoT_Modbus.csv",
                        "ToN_IoT (UNSW Canberra) - IoT telemetry", "public research dataset", "IIoT telemetry (OT protocol)"),
    "iot_motion_light":(DATA_RAW / "ton_iot_gh/Train_Test_IoT_dataset/Train_Test_IoT_Motion_Light.csv",
                        "ToN_IoT (UNSW Canberra) - IoT telemetry", "public research dataset", "IIoT telemetry"),
    "iot_thermostat":  (DATA_RAW / "ton_iot_gh/Train_Test_IoT_dataset/Train_Test_IoT_Thermostat.csv",
                        "ToN_IoT (UNSW Canberra) - IoT telemetry", "public research dataset", "IIoT telemetry"),
    "iot_weather":     (DATA_RAW / "ton_iot_gh/Train_Test_IoT_dataset/Train_Test_IoT_Weather.csv",
                        "ToN_IoT (UNSW Canberra) - IoT telemetry", "public research dataset", "IIoT telemetry"),
    "network_flow":    (DATA_RAW / "netrepo/data/TON_IoT_Train_Test_Network.csv",
                        "ToN_IoT (UNSW Canberra) - Zeek network flows", "public research dataset", "Network activity"),
    "access_log":      (DATA_RAW / "synthetic_remote_access_log.csv",
                        "Generated by src/s02 (documented rules, seed 3815)", "SYNTHETIC", "Identity/access activity"),
    "asset_inventory": (DATA_RAW / "mining_asset_inventory.csv",
                        "Generated by src/s02", "SYNTHETIC", "Asset/device context"),
    "user_directory":  (DATA_RAW / "mining_user_directory.csv",
                        "Generated by src/s02", "SYNTHETIC", "User/account context"),
    "tickets":         (DATA_RAW / "synthetic_maintenance_tickets.csv",
                        "Generated by src/s03", "SYNTHETIC", "Unstructured maintenance/incident text"),
    "attack_ics_text": (DATA_RAW / "attack_ics_text.csv",
                        "MITRE ATT&CK for ICS (STIX bundle)", "public, attribution required",
                        "Unstructured threat-intelligence text"),
}

TIME_PAT = re.compile(r"(^ts$|time|date|_at$)", re.I)
USER_PAT = re.compile(r"(user|account|username|reported_by)", re.I)
DEV_PAT = re.compile(r"(asset|device|host|machine|sensor)", re.I)
IP_PAT = re.compile(r"(ip$|ip_|_ip|address)", re.I)
NET_PAT = re.compile(r"(port|proto|service|bytes|pkts|conn_state|duration|dns|ssl|http|weird)", re.I)
AUTH_PAT = re.compile(r"(auth|mfa|login|logon|privile|result|session)", re.I)
LABEL_PAT = re.compile(r"^(label|type|category|gt_|attack)", re.I)


def semantic_role(col: str, series: pd.Series) -> str:
    c = col.strip()
    if LABEL_PAT.search(c):
        return "security_label"
    if TIME_PAT.search(c):
        return "timestamp"
    if IP_PAT.search(c):
        return "ip_address"
    if USER_PAT.search(c):
        return "user_account"
    if DEV_PAT.search(c):
        return "device_asset"
    if AUTH_PAT.search(c):
        return "authentication_access"
    if NET_PAT.search(c):
        return "network_field"
    if series.dtype == object and series.astype(str).str.split().str.len().mean() > 8:
        return "unstructured_text"
    if pd.api.types.is_numeric_dtype(series):
        return "numeric"
    return "categorical"


def main() -> None:
    inv_rows, dict_rows, qual_rows = [], [], []

    for key, (path, prov, status, role) in SOURCES.items():
        if not path.exists():
            LOG.warning("missing source %s", path)
            continue
        df = pd.read_csv(path, encoding="utf-8-sig", low_memory=False)
        df.columns = [c.strip() for c in df.columns]

        # time coverage, if any timestamp-like column exists
        tmin = tmax = ""
        if "ts" in df.columns:
            t = pd.to_datetime(df["ts"], unit="s", errors="coerce")
        else:
            tcols = [c for c in df.columns if TIME_PAT.search(c)]
            t = pd.to_datetime(df[tcols[0]], errors="coerce") if tcols else None
        if t is not None and t.notna().any():
            tmin, tmax = str(t.min()), str(t.max())

        dup = int(df.duplicated().sum())
        miss = int(df.isna().sum().sum())
        label_col = "label" if "label" in df.columns else ("category" if "category" in df.columns else "")
        inv_rows.append({
            "dataset": key,
            "file": path.name,
            "relative_path": str(path.relative_to(DATA_RAW.parent.parent)),
            "rows": len(df),
            "columns": df.shape[1],
            "size_mb": round(path.stat().st_size / 1e6, 2),
            "sha256": sha256(path)[:16],
            "provenance": prov,
            "data_status": status,
            "project_role": role,
            "time_from": tmin,
            "time_to": tmax,
            "duplicate_rows": dup,
            "duplicate_pct": round(100 * dup / max(len(df), 1), 2),
            "missing_cells": miss,
            "labelled": bool(label_col),
            "label_column": label_col,
            "n_classes": int(df[label_col].nunique()) if label_col else 0,
        })

        for col in df.columns:
            s = df[col]
            nun = int(s.nunique(dropna=True))
            ex = s.dropna().astype(str).unique()[:3]
            dict_rows.append({
                "dataset": key,
                "column": col,
                "dtype": str(s.dtype),
                "semantic_role": semantic_role(col, s),
                "non_null": int(s.notna().sum()),
                "missing_pct": round(100 * s.isna().mean(), 2),
                "n_unique": nun,
                "is_constant": nun <= 1,
                "example_values": " ; ".join(ex),
            })
            if s.isna().mean() > 0.30:
                qual_rows.append({"dataset": key, "issue": "high_missingness", "detail": col,
                                  "value": round(100 * s.isna().mean(), 2)})
            if nun <= 1:
                qual_rows.append({"dataset": key, "issue": "constant_column", "detail": col, "value": nun})
            if s.dtype == object and s.astype(str).str.strip().ne(s.astype(str)).any():
                qual_rows.append({"dataset": key, "issue": "whitespace_padding", "detail": col, "value": ""})
            if s.dtype == object and s.isin(["-", "0.0.0.0", "none", "None", "NULL"]).any():
                qual_rows.append({"dataset": key, "issue": "placeholder_value_token", "detail": col,
                                  "value": int(s.isin(["-", "0.0.0.0", "none", "None", "NULL"]).sum())})
        if dup:
            qual_rows.append({"dataset": key, "issue": "duplicate_rows", "detail": "full-row duplicates",
                              "value": dup})
        LOG.info("%-16s rows=%-8d cols=%-3d dup=%-6d labelled=%s", key, len(df), df.shape[1], dup, bool(label_col))

    inv = pd.DataFrame(inv_rows)
    dic = pd.DataFrame(dict_rows)
    qual = pd.DataFrame(qual_rows)
    inv.to_csv(OUT_TABLES / "data_inventory.csv", index=False)
    dic.to_csv(OUT_TABLES / "data_dictionary.csv", index=False)
    qual.to_csv(OUT_TABLES / "data_quality.csv", index=False)

    summary = {
        "datasets": int(len(inv)),
        "total_records": int(inv["rows"].sum()),
        "distinct_source_families": ["ToN_IoT IIoT telemetry", "ToN_IoT network flows",
                                     "Synthetic remote-access log", "Synthetic ticket text",
                                     "MITRE ATT&CK for ICS text"],
        "labelled_datasets": inv.loc[inv.labelled, "dataset"].tolist(),
        "text_records": int(inv.loc[inv.dataset.isin(["tickets", "attack_ics_text"]), "rows"].sum()),
        "env": env_stamp(),
    }
    write_json(summary, OUT_TABLES / "inventory_summary.json")
    LOG.info("TOTAL records across all sources: %s", f"{summary['total_records']:,}")
    LOG.info("unstructured text records: %s", summary["text_records"])


if __name__ == "__main__":
    main()
