"""
Stage 17 - Member A evidence pack (data and modelling lead deliverables).

The capstone specification, section 4.1, requires Member A to produce a data dictionary,
scripts/notebooks, an experiment log and a model evaluation. Those artefacts exist as CSV
and JSON across outputs/tables/, but a marker should not have to assemble them. This script
generates the three readable documents from the pipeline outputs, so every number in them
is the number the code produced on the last run.

Generated:
  docs/member_a_data_dictionary.md
  docs/member_a_model_evaluation.md
  docs/experiment_log.csv
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import OUT_TABLES, ROOT, get_logger

LOG = get_logger("s17_member_a")
DOCS = ROOT / "docs"
DOCS.mkdir(exist_ok=True)


def tbl(name: str) -> pd.DataFrame:
    return pd.read_csv(OUT_TABLES / name)


def js(name: str) -> dict:
    return json.loads((OUT_TABLES / name).read_text())


# --------------------------------------------------------------------------------------
# 1. Data dictionary document
# --------------------------------------------------------------------------------------
def data_dictionary() -> None:
    inv = tbl("data_inventory.csv")
    dic = tbl("data_dictionary.csv")
    clog = tbl("cleaning_log.csv")
    qual = tbl("data_quality.csv")

    lines = [
        "# Data inventory and data dictionary",
        "",
        "*Member A deliverable (data and modelling lead). Generated by "
        "`src/s17_member_a_pack.py` from the last pipeline run, so the figures match the "
        "code output exactly.*",
        "",
        "## 1. Inventory",
        "",
        f"{len(inv)} files, **{inv['rows'].sum():,} records** in total, drawn from five "
        "source families.",
        "",
        "| Dataset | Rows | Cols | Status | Role in the project | Time coverage | "
        "Duplicates | Labelled |",
        "|---|---:|---:|---|---|---|---:|---|",
    ]
    for r in inv.itertuples():
        cover = f"{str(r.time_from)[:10]} to {str(r.time_to)[:10]}" if str(r.time_from) != "nan" else "n/a"
        lines.append(f"| `{r.dataset}` | {r.rows:,} | {r.columns} | {r.data_status} | "
                     f"{r.project_role} | {cover} | {r.duplicate_rows:,} | "
                     f"{'yes (' + str(r.label_column) + ')' if r.labelled else 'no'} |")

    lines += [
        "",
        "Provenance hashes (SHA-256, first 16 characters) are stored in "
        "`outputs/tables/data_inventory.csv` so that a marker can confirm the raw inputs "
        "were not edited after analysis.",
        "",
        "## 2. Column dictionary by semantic role",
        "",
        "Each column was classified automatically into the role it plays in the analysis. "
        "This is how requirement C2 is demonstrated: identity/access, network/OT and "
        "asset-context fields all exist in the data, not only in the proposal.",
        "",
    ]
    role_counts = dic["semantic_role"].value_counts()
    lines.append("| Semantic role | Columns | Datasets |")
    lines.append("|---|---:|---|")
    for role, n in role_counts.items():
        ds = ", ".join(sorted(dic.loc[dic.semantic_role == role, "dataset"].unique())[:6])
        lines.append(f"| {role} | {n} | {ds} |")
    lines.append("")

    for ds in inv["dataset"]:
        sub = dic[dic.dataset == ds]
        if sub.empty:
            continue
        lines += [f"### `{ds}`", "",
                  "| Column | Type | Role | Non-null | Missing % | Distinct | Example |",
                  "|---|---|---|---:|---:|---:|---|"]
        for r in sub.itertuples():
            ex = str(r.example_values)[:48].replace("|", "/")
            lines.append(f"| `{r.column}` | {r.dtype} | {r.semantic_role} | {r.non_null:,} | "
                         f"{r.missing_pct} | {r.n_unique:,} | {ex} |")
        lines.append("")

    lines += [
        "## 3. Quality findings",
        "",
        f"{len(qual)} quality issues were recorded automatically before any cleaning was "
        "applied. The most common categories were:",
        "",
    ]
    for issue, n in qual["issue"].value_counts().items():
        lines.append(f"- **{issue}** - {n} occurrences")
    lines += [
        "",
        "## 4. Cleaning actions",
        "",
        f"{len(clog)} actions were logged. Every action records the dataset, what was done, "
        "why, and the row count before and after, so nothing changes silently.",
        "",
        "| Dataset | Action | Detail | Reason |",
        "|---|---|---|---|",
    ]
    for r in clog.itertuples():
        lines.append(f"| {r.dataset} | {r.action} | {str(r.detail)[:60]} | "
                     f"{str(r.reason)[:110]} |")
    lines += [
        "",
        "## 5. Decisions a marker may want to question",
        "",
        "- **Duplicates are flagged, not deleted, in the stored data.** The flag is used to "
        "exclude them from model training and testing, but the rows stay in the file so "
        "that no evidence is destroyed.",
        "- **Missing telemetry values are not imputed.** A gap in a sensor feed is treated "
        "as a gap, because an invented reading would teach the model a pattern that never "
        "happened.",
        "- **Zeek's `-` placeholder is treated as missing, not as a category.** Left as a "
        "string it would have become one of the strongest, and entirely artificial, "
        "predictors.",
        "- **The ToN_IoT flow mirror has no timestamp column**, so joins to that source are "
        "made on address and asset rather than on time. This is recorded as defect D01.",
        "",
    ]
    (DOCS / "member_a_data_dictionary.md").write_text("\n".join(lines), encoding="utf-8")
    LOG.info("data dictionary document written (%d columns documented)", len(dic))


# --------------------------------------------------------------------------------------
# 2. Model evaluation report
# --------------------------------------------------------------------------------------
def model_evaluation() -> None:
    sup = js("supervised_summary.json")
    anom = js("anomaly_summary.json")
    cv = tbl("supervised_network_cv.csv")
    test = tbl("supervised_network_test.csv")
    mb = tbl("supervised_modbus_test.csv")
    multi = pd.read_csv(OUT_TABLES / "supervised_network_multiclass.csv", index_col=0)
    imp = tbl("supervised_network_importance.csv")
    thr = tbl("anomaly_network_thresholds.csv")
    thrb = tbl("anomaly_network_baseline_thresholds.csv")
    accval = tbl("anomaly_access_validation.csv")
    adv = tbl("adversarial_results.csv")
    risk = js("risk_adversarial_summary.json")
    bal = sup["network"]["class_balance"]

    def row(df, model):
        return df[df.model == model].iloc[0]

    rf, dt, lr = row(test, "random_forest"), row(test, "decision_tree"), row(test, "logistic_regression")

    lines = [
        "# Model evaluation report",
        "",
        "*Member A deliverable (data and modelling lead). Every figure is read from the "
        "pipeline outputs by `src/s17_member_a_pack.py`; nothing is typed in by hand.*",
        "",
        "## 1. What was modelled, and why",
        "",
        "Three modelling problems were set, each matching a question in the charter:",
        "",
        "1. **Network intrusion detection** on ToN_IoT Zeek flows - can an attack flow be "
        "separated from ordinary traffic? (charter question 1)",
        "2. **Attack family identification** - if it is an attack, which kind? This decides "
        "which playbook an analyst opens.",
        "3. **OT protocol abuse** on Modbus telemetry - the mining-specific case, since "
        "Modbus is the protocol that touches physical plant.",
        "",
        "## 2. Preparation and leakage control",
        "",
        f"The flow dataset contains **{sup['network']['rows_dropped_as_duplicate']:,} exact "
        f"duplicate rows**. These were removed *before* the train/test split, leaving "
        f"{sup['network']['rows_used']:,} rows. Splitting first would have allowed the same "
        "record to appear on both sides of the split and would have inflated every score.",
        "",
        f"Class balance in the modelling set: **{bal['attack']:,} attack** rows and "
        f"**{bal['normal']:,} normal** rows, so attacks are "
        f"{bal['attack_share']:.0%} of the data. The minority class here is *normal* "
        "traffic, which is the opposite of an operational network and matters for the "
        "anomaly work in section 5. Class weighting was applied in every classifier so the "
        "imbalance does not simply push predictions towards the majority.",
        "",
        "Features: 18 numeric flow measures (durations, byte and packet counts, ratios and "
        "logarithmic transforms, ports) and 3 categorical fields (`proto`, `service`, "
        "`conn_state`), one-hot encoded with rare categories grouped.",
        "",
        "## 3. Model selection",
        "",
        "Selection used 3-fold cross-validated F1 on the **training data only**. The test "
        "set was scored once, at the end.",
        "",
        "| Model | CV F1 (mean) | CV F1 (sd) |",
        "|---|---:|---:|",
    ]
    for r in cv.itertuples():
        lines.append(f"| {r.model} | {r.cv_f1_mean:.4f} | {r.cv_f1_sd:.4f} |")

    lines += [
        "",
        f"**Random Forest** was selected. The justification is not that it scored highest "
        "by a fraction, but that flow data is a mixture of skewed numeric measures and "
        "categorical protocol fields with strong interactions, which is exactly the "
        "structure a tree ensemble handles without scaling assumptions. Logistic regression "
        "is retained as a transparent baseline, and the decision tree as an auditable "
        "rule set an OT engineer can read.",
        "",
        "## 4. Held-out performance",
        "",
        "| Model | Accuracy | Precision | Recall | F1 | ROC-AUC | PR-AUC |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for r in test.itertuples():
        lines.append(f"| {r.model} | {r.accuracy:.4f} | {r.precision:.4f} | {r.recall:.4f} | "
                     f"{r.f1:.4f} | {r.roc_auc:.4f} | {r.pr_auc:.4f} |")

    lines += [
        "",
        "**Reading these numbers in security terms.** At the Random Forest's operating "
        f"point, recall of {rf.recall:.4f} means roughly "
        f"{(1 - rf.recall) * 10000:.0f} attack flows in every 10,000 would be missed, and "
        f"precision of {rf.precision:.4f} means about "
        f"{(1 - rf.precision) * 10000:.0f} false alarms per 10,000 flagged flows. For a SOC, "
        "the false-alarm rate is what decides whether the detector is usable at all, which "
        "is why precision is reported beside recall rather than accuracy alone.",
        "",
        f"Logistic regression reaches F1 {lr.f1:.4f}, so a large part of this problem is "
        "linearly separable, but it misses "
        f"{(1 - lr.recall) * 100:.1f}% of attacks against "
        f"{(1 - rf.recall) * 100:.1f}% for the forest. On 211,000 flows that difference is "
        "thousands of missed events.",
        "",
        "### Attack family identification",
        "",
        f"Macro-F1 **{sup['network']['multiclass_macro_f1']:.4f}** across "
        f"{len(multi) - 3} labelled families.",
        "",
        "| Family | Precision | Recall | F1 | Support |",
        "|---|---:|---:|---:|---:|",
    ]
    for idx, r in multi.iterrows():
        if idx in ("accuracy", "macro avg", "weighted avg"):
            continue
        lines.append(f"| {idx} | {r['precision']:.3f} | {r['recall']:.3f} | "
                     f"{r['f1-score']:.3f} | {int(r['support']):,} |")
    worst = multi.drop(index=[i for i in ("accuracy", "macro avg", "weighted avg")
                              if i in multi.index])["f1-score"].idxmin()
    lines += [
        "",
        f"The weakest class is **{worst}**, with only "
        f"{int(multi.loc[worst, 'support']):,} test examples. That is a data-volume "
        "limitation rather than a modelling failure, and it should be stated as such: a "
        "class with a few hundred examples cannot be evaluated with confidence.",
        "",
        "### Modbus telemetry (OT protocol)",
        "",
        "| Model | Accuracy | Precision | Recall | F1 |",
        "|---|---:|---:|---:|---:|",
    ]
    for r in mb.itertuples():
        lines.append(f"| {r.model} | {r.accuracy:.4f} | {r.precision:.4f} | {r.recall:.4f} | "
                     f"{r.f1:.4f} |")
    lines += [
        "",
        f"The gap here is the interesting result: logistic regression reaches F1 "
        f"{row(mb, 'logistic_regression').f1:.4f} while the forest reaches "
        f"{row(mb, 'random_forest').f1:.4f}. Register values from a manipulated Modbus "
        "device are not high or low in a straight line; they are abnormal in combination, "
        "so a linear model cannot separate them and a tree ensemble can.",
        "",
        "## 5. What the detector actually uses",
        "",
        "Permutation importance (mean F1 drop when a feature is shuffled):",
        "",
        "| Feature | Importance | SD |",
        "|---|---:|---:|",
    ]
    for r in imp.head(8).itertuples():
        lines.append(f"| `{r.feature}` | {r.importance:.4f} | {r.sd:.4f} |")
    lines += [
        "",
        f"`{imp.iloc[0]['feature']}` dominates. This is worth saying honestly in the "
        "defence: the model leans heavily on protocol and connection-state fields rather "
        "than on traffic volume, which is also why the evasion test in section 7 barely "
        "moves the score - the evasion we simulated changed volume, not protocol.",
        "",
        "## 6. Unsupervised detection",
        "",
        "Two framings were run on the same data, and the contrast is the main methodological "
        "finding of the project.",
        "",
        f"- **Fully unsupervised** (fit on everything, no labels): ROC-AUC "
        f"**{anom['network']['roc_auc_unsupervised']:.3f}** - below chance.",
        f"- **Novelty detection against a known-good baseline** (fit on normal traffic only, "
        f"scored on unseen flows): ROC-AUC **{anom['network']['roc_auc_clean_baseline']:.3f}**.",
        "",
        anom["network"]["interpretation"],
        "",
        "Operating points for the fully unsupervised run:",
        "",
        "| Alert budget (top %) | Flagged | Precision | Recall |",
        "|---|---:|---:|---:|",
    ]
    for r in thr.itertuples():
        lines.append(f"| top {100 * (1 - r.threshold_quantile):.0f}% | {r.flagged:,} | "
                     f"{r.precision:.3f} | {r.recall:.3f} |")
    lines += ["", "Operating points for the clean-baseline run:", "",
              "| Threshold quantile | Flagged | Precision | Recall |", "|---|---:|---:|---:|"]
    for r in thrb.itertuples():
        lines.append(f"| {r.threshold_quantile:.2f} | {r.flagged:,} | {r.precision:.3f} | "
                     f"{r.recall:.3f} |")

    lines += [
        "",
        "### Access behaviour (user-days)",
        "",
        "| Method | Flagged | Precision vs injected | Recall vs injected | ROC-AUC |",
        "|---|---:|---:|---:|---:|",
    ]
    for r in accval.itertuples():
        lines.append(f"| {r.method} | {r.flagged} | {r.precision_vs_injected:.3f} | "
                     f"{r.recall_vs_injected:.3f} | {r.roc_auc_vs_injected:.3f} |")
    lines += [
        "",
        "Isolation Forest separates the injected behaviour almost perfectly; Local Outlier "
        "Factor does not beat chance on the same features. The likely reason is that the "
        "injected behaviour is globally unusual rather than locally unusual - the accounts "
        "concerned sit far from the whole population, not just from their immediate "
        "neighbours - and LOF measures local density.",
        "",
        "**Threshold.** The operating threshold is the 98th percentile of the score, which "
        "flags about 2 per cent of user-days. That is an alerting budget decision, not a "
        "statistical one: it is roughly two cases per working day for a 114-account estate.",
        "",
        "## 7. Robustness and adversarial testing",
        "",
        "| Test | Setting | F1 | Change vs unmodified |",
        "|---|---|---:|---:|",
    ]
    for r in adv.itertuples():
        lines.append(f"| {r.test} | {r.setting} | {r.f1:.4f} | {r.f1_change_vs_baseline:+.4f} |")
    lines += [
        "",
        "**Interpretation.** Collection reliability is the biggest risk: losing half the "
        "fields costs more than a quarter of the F1, so telemetry completeness is itself a "
        "security control. Label poisoning has to reach roughly a third of the training set "
        "before it does comparable damage, which argues for controlling who can label data. "
        "The evasion test is the weakest of the four, because it perturbs volume features "
        "while the model relies on protocol fields - a stronger test is recorded as backlog "
        "item B02 rather than claimed as a result.",
        "",
        "## 8. Predictive risk model",
        "",
        f"The daily risk score separates the injected behaviour with ROC-AUC "
        f"**{risk['risk_score']['roc_auc_vs_injected']:.3f}** and precision at the top 20 "
        f"user-days of **{risk['risk_score']['precision_at_20']:.2f}**.",
        "",
        f"The next-day early-warning model is weak: ROC-AUC "
        f"**{risk['early_warning']['roc_auc']:.3f}** on a time-ordered split, against a base "
        f"rate of {risk['early_warning']['test_positive_rate']:.3f}. This is reported as a "
        "negative result. Alerts in this data are driven by single events rather than by a "
        "build-up in the preceding day's behaviour, so there is little for a next-day model "
        "to learn. A longer observation window, or event-level rather than day-level "
        "features, would be the next thing to try.",
        "",
        "## 9. Limitations that must be stated",
        "",
        "1. ToN_IoT is a controlled testbed. Scores near 1.0 reflect a clean laboratory "
        "capture, not what the same model would achieve on live mining traffic.",
        "2. Attacks are the majority class in the capture, which is unlike any real network "
        "and directly explains the unsupervised result in section 6.",
        "3. The access-behaviour results are measured against behaviour that we injected "
        "ourselves, so they demonstrate that the method works, not that an attacker was "
        "found.",
        "4. The Modbus and flow models are trained on the same testbed environment, so they "
        "would need recalibration against site data before any operational use.",
        "",
    ]
    (DOCS / "member_a_model_evaluation.md").write_text("\n".join(lines), encoding="utf-8")
    LOG.info("model evaluation report written")


# --------------------------------------------------------------------------------------
# 3. Experiment log
# --------------------------------------------------------------------------------------
def experiment_log() -> None:
    """Chronological record of what was tried, what happened and what was decided."""
    sup = js("supervised_summary.json")
    anom = js("anomaly_summary.json")
    risk = js("risk_adversarial_summary.json")
    nlp = js("nlp_summary.json")
    sim = pd.read_csv(OUT_TABLES / "simulation_summary.csv")
    stages = js("experiment_log.json")

    rows = [
        ("E01", "data", "Search for an accessible ToN_IoT mirror",
         "Kaggle and Hugging Face copies require credentials or are blocked",
         "Located public GitHub mirrors for the IoT telemetry and the Zeek flows",
         "Cloned both; documented the clone commands in the README"),
        ("E02", "data", "Check whether the flow mirror carries timestamps",
         "44 columns inspected", "No `ts` column in this mirror",
         "Recorded as defect D01; cross-source joins use address and asset instead of time"),
        ("E03", "data", "Choose an identity/access source for C2",
         "ToN_IoT has no login records; the charter forbids real credentials",
         "Wrote a documented synthetic generator with a fixed seed",
         "Accepted, with the synthetic status stated in every product"),
        ("E04", "data", "Country codes in the access log",
         "ISO-2 code 'NA' used for Namibia",
         "pandas read 'NA' as missing, so every user-day looked foreign (100% flagged)",
         "Switched to ISO-3 codes and added a regression test (defect D02)"),
        ("E05", "features", "Handle Zeek '-' placeholders",
         "211,043 flows, 16 columns above 97% empty",
         "Left as text the placeholder becomes an artificial predictor",
         "Converted to missing; sparse columns excluded from features"),
        ("E06", "supervised", "Compare LR, decision tree and random forest",
         "3-fold CV F1 on the training split only",
         f"RF {sup['network']['cv'][2]['cv_f1_mean']:.4f}, DT "
         f"{sup['network']['cv'][1]['cv_f1_mean']:.4f}, LR "
         f"{sup['network']['cv'][0]['cv_f1_mean']:.4f}",
         "Random Forest selected; the other two kept as interpretable comparators"),
        ("E07", "supervised", "Duplicate leakage check",
         f"{sup['network']['rows_dropped_as_duplicate']:,} exact duplicates found",
         "Removing them before the split changes the evaluation honestly",
         "Duplicates flagged in the data and excluded from train and test"),
        ("E08", "supervised", "Modbus telemetry classifier",
         "Registers plus hour and day-of-week features",
         f"RF F1 {sup['modbus']['metrics'][1]['f1']:.4f} against LR "
         f"{sup['modbus']['metrics'][0]['f1']:.4f}",
         "Kept both to show that the OT signal is non-linear"),
        ("E09", "anomaly", "Isolation Forest on flows, fully unsupervised",
         "80,000-flow sample, contamination 0.15",
         f"ROC-AUC {anom['network']['roc_auc_unsupervised']:.3f} - below chance because "
         "attacks are the majority class",
         "Kept and reported as a finding rather than discarded"),
        ("E10", "anomaly", "Isolation Forest fitted on known-good traffic only",
         "60% of normal flows used for fitting, remainder held out",
         f"ROC-AUC {anom['network']['roc_auc_clean_baseline']:.3f} on "
         "held-out flows",
         "Adopted as the realistic framing for an OT site"),
        ("E11", "anomaly", "LOF as a contrasting method on user-days",
         "25 neighbours, same feature set as the Isolation Forest",
         f"ROC-AUC {anom['access']['validation'][1]['roc_auc_vs_injected']:.3f} versus "
         f"{anom['access']['validation'][0]['roc_auc_vs_injected']:.3f} for IF",
         "IF retained for the prototype; LOF reported as a negative comparison"),
        ("E12", "access", "Threshold for the failed-login burst rule",
         "Baseline 99th percentile is 2 failures per day; no account exceeded 3 per hour",
         "A threshold of 5 per hour produced no alerts at all",
         "Lowered to 3 per hour, justified against the measured baseline"),
        ("E13", "access", "Out-of-hours privileged action rule (R4)",
         "Per-account 5th-95th percentile working window",
         "99 alerts at 4% precision against injected behaviour",
         "Kept deliberately as the tuning counter-example; flagged as defect D07"),
        ("E14", "simulation", "First network graph was too densely connected",
         "3,547 edges, 20 steps",
         "Every scenario compromised about 177 of 195 assets, so controls looked useless",
         "Sparsened the OT and IT meshes, lowered base probabilities, shortened the horizon"),
        ("E15", "simulation", "MFA modelled on internal edges",
         "MFA factor applied to the gateway edge",
         "No effect, because the foothold node is already compromised at step 0",
         "Moved the MFA effect onto the foothold probability, which is where it acts"),
        ("E16", "simulation", "Final scenario comparison",
         "5 scenarios x 5,000 runs, Wilson intervals",
         f"P(reach OT): baseline {sim.iloc[0]['p_reach_ot']:.3f} to combined "
         f"{sim.iloc[4]['p_reach_ot']:.3f}",
         "Ranking stable across all sensitivity scales"),
        ("E17", "nlp", "Ticket classification",
         "TF-IDF (1-2 grams) with logistic regression, 30% held out",
         f"macro-F1 {nlp['classification']['macro_f1']:.3f} - optimistic because the "
         "corpus is template-generated",
         "Kept, with the caveat recorded in the outputs and repeated in the report"),
        ("E18", "nlp", "Indicator extraction scored against an answer key",
         "Regular expressions plus an ATT&CK malware gazetteer",
         f"precision {nlp['indicator_extraction']['precision']:.3f}, recall "
         f"{nlp['indicator_extraction']['recall']:.3f}",
         "Accepted; false positives come from extra entities not in the answer key"),
        ("E19", "risk", "Risk band cut-points",
         "Components are percentile ranks, so an average account scores about 50",
         "Fixed cut-points put 44% of user-days in the 'high' band",
         "Cut-points moved to score quantiles (0.900, 0.980, 0.995) as an alert budget"),
        ("E20", "risk", "Next-day early warning",
         "Time-ordered split, logistic regression on day-level features",
         f"ROC-AUC {risk['early_warning']['roc_auc']:.3f} against a base rate of "
         f"{risk['early_warning']['test_positive_rate']:.3f}",
         "Reported as a negative result rather than tuned until it looked better"),
        ("E21", "adversarial", "First robustness baseline was computed on training rows",
         "40,000-row sample drawn from the whole dataset",
         "Reference F1 was inflated relative to the true held-out score",
         "Stage-08 split reproduced exactly; only test rows are perturbed (defect D04)"),
        ("E22", "adversarial", "Four perturbation families",
         "Drift, evasion, missing data, label poisoning, three severities each",
         "Largest loss is missing data at 50% (F1 -0.23); evasion costs almost nothing",
         "Evasion test recorded as insufficient; backlog item B02"),
        ("E23", "pipeline", "End-to-end reproducibility run",
         f"{len(stages['stages'])} stages from raw data to compliance checklist",
         f"Completed in {stages['total_seconds']:.0f} seconds; 16 test cases pass",
         "Accepted as the Milestone 2 baseline"),
    ]
    df = pd.DataFrame(rows, columns=["id", "area", "experiment", "setup", "result",
                                     "decision"])
    df.to_csv(DOCS / "experiment_log.csv", index=False)
    LOG.info("experiment log written (%d entries)", len(df))


def main() -> None:
    data_dictionary()
    model_evaluation()
    experiment_log()


if __name__ == "__main__":
    main()
